# Generated by Django 2.0.5 on 2018-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('card_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=254)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
