# Generated by Django 2.0.5 on 2018-05-31 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField()),
                ('renewal_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Partner', 'Partner'), ('Client', 'Client')], default='Client', max_length=10)),
                ('card_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discountCard.Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
