# Generated by Django 2.0.5 on 2018-06-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discountCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_number',
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='discountCard.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Larnaka', 'Larnaka'), ('Paralimni', 'Paralimni'), ('Limassol', 'Limassol'), ('Nicosia', 'Nicosia'), ('Paphos', 'Paphos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Cyprus', 'Cyprus'), ('Greece', 'Greece')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Partner', 'Partner')], default='Client', max_length=10),
        ),
    ]
