# Generated by Django 2.0.5 on 2018-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountCard', '0002_auto_20180609_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Partner', 'Partner'), ('Client', 'Client')], default='Client', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Paphos', 'Paphos'), ('Paralimni', 'Paralimni'), ('Nicosia', 'Nicosia'), ('Larnaka', 'Larnaka'), ('Limassol', 'Limassol')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Greece', 'Greece'), ('Cyprus', 'Cyprus')], default='', max_length=10),
        ),
    ]
