# Generated by Django 2.0.5 on 2018-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountCard', '0003_auto_20180609_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Partner', 'Partner')], default='Client', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Nicosia', 'Nicosia'), ('Paralimni', 'Paralimni'), ('Larnaka', 'Larnaka'), ('Limassol', 'Limassol'), ('Paphos', 'Paphos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Cyprus', 'Cyprus'), ('Greece', 'Greece')], default='', max_length=10),
        ),
    ]
