# Generated by Django 2.0.5 on 2018-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountCard', '0009_auto_20180622_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Synolic Visitors', 'Synolic Visitors'), ('Synolic Youth', 'Synolic Youth'), ('Synolic Personal', 'Synolic Personal'), ('Synolic Corporate', 'Synolic Corporate')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Limassol', 'Limassol'), ('Paphos', 'Paphos'), ('Paralimni', 'Paralimni'), ('Larnaka', 'Larnaka'), ('Nicosia', 'Nicosia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Cyprus', 'Cyprus'), ('Greece', 'Greece')], default='', max_length=10),
        ),
    ]
